version: '3'
services:
  db2server:
    container_name: db2server
    image: ibmcom/db2
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=test
      - DBNAME=testdb
      - PERSISTENT_HOME=false
    volumes:
      - './db2data:/database'
    ports:
      - '50000:50000'    
    privileged: true
